title: Haoyu Han's Site
logo: /assets/img/img.png
description: A simple homepage of my website....
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# 新的变量定义
sidebar_links:
  - title: "Name"
    url: "Haoyu Han"
  - title: "School"
    url: "BIT"
  - title: "Location"
    url: "Beijing, China"
  - title: "Email"
    url: "hyhan@bit.edu.cn"
